### ISSUE TITLE
blogsyncのglobal config読み込みの非互換変更に関する相談

### ISSUE THREAD

**Issue by Songmu** [hatena/hatenablog-workflows#20]
ref. https://github.com/x-motemen/blogsync/pull/87 

global config (`~/.config/blogsync/config.yaml`) のlocal_rootに相対パスが指定されていたとき、今は blogsync 実行パスからの相対位置に解決されるようになっています。この挙動はblogsyncの実行位置によってpullされてくるディレクトリが変わることもあって、気持ち悪い挙動なので、変更したいと考えています。

一般的には、相対パスが指定されていた場合、設定ファイルからの相対位置に解決されるのがよくある挙動だと考え、上記のpull requestではその方針で実装しています。

ただ、global configからの相対位置に解決されるのは、直感的な挙動とは言いづらく、既存のユーザーが相対パスに設定していた場合に意図せず、これまでと違う位置にpull されるのはあまり嬉しい挙動だとは思えません。また、global configにはそもそも相対パスが設定されること自体が望ましくないとも思います。

なので、global configには相対パスの指定を禁止し、設定されていた場合にはエラー終了とすることも考えています。

何にせよ非互換変更になるのでこちらで相談しました。このワークフローではローカル設定 (blogsync.yaml) しか見ないようになっていると思うので、特に問題ないのではないかと思っていますが、ご意見あればよろしくお願いします。

**Comment by halkt** [comment]
わざわざご連絡いただきありがとうございます!

上記の変更については違和感はありません. また, 本仕組みの動作にも大きな影響はなさそうでしたので変更してくださっても大丈夫かと思います.

**Comment by halkt** [comment]
@Songmu 

わざわざご連絡いただきありがとうございます!

上記の変更については違和感はありません. また, 本仕組みの動作にも大きな影響はなさそうでしたので変更してくださっても大丈夫かと思います.
