### ISSUE TITLE
blogsyncの更新との協調について

### ISSUE THREAD

**Issue by Songmu** [hatena/hatenablog-workflows#27]
最近良くも悪くもblogsyncのメンテにやる気を出してしまっているのですが、逆に、こちらのワークフローとの互換問題が出やすくなっていると思います。

また、blogsync側の機能拡張してやったほうが良いのか、このワークフロー側でやったほうが良いのかの役割分担も検討したほうが良いでしょう。個人的所見としては、こちらのワークフローもちょっと頑張り過ぎで、blogsync側を拡張してやったほうが良いものを、ワークフロー側でblogysyncが想定していない使い方で無理に解決している分壊れやすくなっているとも思います。実際URL周りで最近エンバグしていました。 https://github.com/x-motemen/blogsync/pull/99

このあたりはちょっとメンテナンス方針を協議したほうが良いように感じています。少なくとも、古いblogsyncバージョンに固定し続けるのはあまり良くないと思います。

また、最近入れた更新で、このワークフロー側で有用そうな変更をお知らせします。
## blogsyncが標準出力に更新されたファイルパスを出すように

https://github.com/x-motemen/blogsync/pull/107

```
entry_path=$(blogsync post ...)
```

上記のようにすれば、更新や新規作成されたエントリーのファイルパスが取れるようになったので、 `create-draft.yaml` でタイトル名からファイルを解決する挙動がありますが、それが不要になると思います。

## 下書きを除外してpullする

https://github.com/x-motemen/blogsync/pull/110

```
blogsync pull --no-drafts
```

`blogsync pull` 後にDraftを消し去っているところがあると思いますが、 `--no-drafts` オプションで同様のことを実現できるようになりました。

**Comment by halkt** [comment]
ご連絡ありがとうございます!今後の機能拡張については個別にそうだんをさせていただこうと思います!

> 少なくとも、古いblogsyncバージョンに固定し続けるのはあまり良くないと思います。

こちらはその通りなので, 近日対応予定です!

**Comment by halkt** [comment]
@Songmu 

blogsyncのバージョン固定の解除を行いました
https://github.com/hatena/hatenablog-workflows/pull/29
