### ISSUE TITLE
pull draftでタイトル指定を不要にする

### ISSUE THREAD

**Issue by Songmu** [hatena/hatenablog-workflows#28]
タイトルを引かずとも、下書きになっているエントリーを一通り取得してきて、下書きそれぞれに対してブランチを切って、下書きの数だけpull requestを作る挙動にした方がイージーかと思いました。(エントリーIDがブランチ名に含まれているのですでに作られている場合にはスキップすれば良い)

そちらのほうがcron実行などとも連携がしやすいというメリットもあります。

そんなに下書きが何十とあるようなblogも少ないと思うので。

**Comment by halkt** [comment]
ご提案ありがとうございます!
チーム内で検討検討をさせていただきます

**Comment by airreader** [comment]
こちら一旦 not planned とさせてください。理由は以下の通りです。

- 「下書きの記事タイトル」という固有でない値を指定して記事を特定する仕様がなくなるのはポジティブ
- 一方、下書きが多いブログは存在しており、はてな内でも数十件単位で保有しているブログもあった
- 自分の下書きの操作を行いたいだけなのに、他のユーザーの下書きのプルリクエストが生成されてしまうのが気になるかもしれない
- メリットもあるがデメリットも考えられそうで現状では判断できない。ユーザーからフィードバックを受けながら検討したい

ご提案ありがとうございました。需要がありそうであれば、既存のアクションとは別にアクションを用意しても良いかもですね。
