### ISSUE TITLE
crate-draft 実行時に過去記事に比例して API アクセスが増える

### ISSUE THREAD

**Issue by Mahito** [hatena/hatenablog-workflows#59]
該当の job を実行すると過去記事数に応じてAPI アクセスが増加します。

https://github.com/hatena/hatenablog-workflows/blob/e66f8afc3f67f317756a4c89e8c309f7eac0300a/.github/workflows/create-draft.yaml#L43-45

所有する記事に毎回 GET が走るように見えているため、
`blogsync fetch ${{ steps.post-draft.outputs.ENTRY_PATH }}` とかに置き換えができれば良いかなと思いますがいかがでしょうか。

**Comment by airreader** [comment]
ご指摘ありがとうございます！こちら対応を予定しております。

**Comment by halkt** [comment]
提案ありがとうございます!
こちらは https://github.com/hatena/hatenablog-workflows/pull/64 にて解消しましたのでクローズします!
