### ISSUE TITLE
fotolife-client.pyに画像ファイルが見つからずに何もしなかった時のメッセージを出したいです

### ISSUE THREAD

**Issue by morihaya** [hatena/hatenablog-workflows#91]
タイトルの理由でPR #90 を作成させていただきました。

長年はてなブログにはお世話になっています。
今更ながら https://github.com/hatena/Hatena-Blog-Workflows-Boilerplate の存在を知り、これまでのWeb上での編集からGitHub管理へ移行し検証している中で、GitHub Actionsのpush-draft.yamlによるupload-imageで画像がアップされない事象に遭遇しました。

原因はPR内にも書きましたがパスの指定不備です。

詳細として、私はPCローカルでの下書きをVisual Studio Code(VSC)で行なっており、プレビュー機能を使いながら記事を書いています。
VSCでは以下のような”OSとしては存在しないパス”でもプレビューに画像が表示されるため、「ローカルでは画像が表示されるのに、リモートのCIだと画像ファイルとして認識されない」状況になり混乱しました。

例: VSCだとプレビューで表示されるがOSとしてはおかしいパス `/images/hoge.png`

手元でデバッグをしたところ、今回のPRで出したprintによって事象を発見できましたので、同じハマり方をする方が少しでも楽ができると良いと考えパッチのPRを送ります。

**Comment by airreader** [comment]
PRの作成ありがとうございました！大変助かります

**Comment by morihaya** [comment]
取り込みありがとうございます！！！
